/**
 * Word Report Service
 * 
 * Generates Word (.docx) reports from the same HTML template used for PDF.
 * Ensures PDF and Word content is identical.
 */

const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableCell, TableRow, WidthType, BorderStyle } = require('docx');
const fs = require('fs').promises;
const path = require('path');
const { convert } = require('html-to-docx');

/**
 * Generate Word document from HTML content
 * 
 * @param {string} htmlContent - Full HTML report content
 * @param {string} outputPath - Where to save the .docx file
 * @returns {Promise<{ success: boolean, filePath: string, fileSize: number }>}
 */
async function generateWordFromHtml(htmlContent, outputPath) {
  try {
    console.log('📝 Generating Word document from HTML...');

    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    // Convert HTML to DOCX buffer using html-to-docx library
    // This library preserves formatting, tables, headings, etc.
    const docxBuffer = await convert(htmlContent, {
      orientation: 'portrait',
      margins: {
        top: 1440, // 1 inch in twips (1440 twips = 1 inch)
        right: 1440,
        bottom: 1440,
        left: 1440
      },
      font: 'Calibri',
      fontSize: 22, // 11pt (size is in half-points)
      lineHeight: 360, // 1.5 line spacing
      title: 'Ethical AI Assessment Report',
      subject: 'Z-Inspection Report',
      creator: 'Z-Inspection Platform',
      keywords: ['ethical AI', 'assessment', 'governance'],
      description: 'Enterprise-grade ethical assessment report'
    });

    // Write buffer to file
    await fs.writeFile(outputPath, docxBuffer);

    // Get file size
    const stats = await fs.stat(outputPath);
    const fileSize = stats.size;

    console.log(`✅ Word document generated successfully: ${outputPath} (${(fileSize / 1024).toFixed(2)} KB)`);

    return {
      success: true,
      filePath: outputPath,
      fileSize
    };
  } catch (error) {
    console.error('❌ Error generating Word document:', error);
    throw new Error(`Word generation failed: ${error.message}`);
  }
}

/**
 * Fallback: Generate simple Word document using docx library
 * Used if html-to-docx fails or is not available
 * 
 * @param {Object} analysisData - Report data (same as used for PDF)
 * @param {string} outputPath - Where to save the .docx file
 * @returns {Promise<{ success: boolean, filePath: string, fileSize: number }>}
 */
async function generateWordFromData(analysisData, outputPath) {
  try {
    console.log('📝 Generating Word document from data (fallback mode)...');

    const { project, reportMetrics, narrative } = analysisData;

    // Create document with basic structure
    const doc = new Document({
      creator: 'Z-Inspection Platform',
      title: `Ethical Assessment Report - ${project.name}`,
      description: 'Ethical AI Assessment Report',
      sections: [
        {
          properties: {
            page: {
              margin: {
                top: 1440,
                right: 1440,
                bottom: 1440,
                left: 1440
              }
            }
          },
          children: [
            // Title
            new Paragraph({
              text: 'Ethical AI Assessment Report',
              heading: HeadingLevel.HEADING_1,
              alignment: AlignmentType.CENTER,
              spacing: { after: 400 }
            }),

            // Project info
            new Paragraph({
              text: `Project: ${project.name || 'N/A'}`,
              spacing: { after: 200 }
            }),

            new Paragraph({
              text: `Generated: ${new Date().toLocaleString()}`,
              spacing: { after: 400 }
            }),

            // Executive Summary
            new Paragraph({
              text: 'Executive Summary',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 400, after: 200 }
            }),

            new Paragraph({
              text: narrative?.slice(0, 500) || 'Report content generated by Gemini.',
              spacing: { after: 400 }
            }),

            // Metrics
            new Paragraph({
              text: 'Overall Risk Assessment',
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 400, after: 200 }
            }),

            new Paragraph({
              children: [
                new TextRun({ text: 'Overall Ethical Risk Score: ', bold: true }),
                // Use safeToFixed + fallback to totals.overallAvg
                new TextRun({ text: `${(reportMetrics?.scoring?.totals?.overallAvg || 0).toFixed(2)}` })
              ],
              spacing: { after: 100 }
            }),

            new Paragraph({
              children: [
                new TextRun({ text: 'Risk Classification: ', bold: true }),
                new TextRun({ text: reportMetrics?.scoring?.totalsOverall?.riskLabel || 'N/A' })
              ],
              spacing: { after: 400 }
            }),

            // Footer note
            new Paragraph({
              text: 'Note: This is a simplified Word export. For full report with visualizations, use PDF format.',
              italics: true,
              spacing: { before: 800 }
            })
          ]
        }
      ]
    });

    // Generate buffer
    const buffer = await Packer.toBuffer(doc);

    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    // Write to file
    await fs.writeFile(outputPath, buffer);

    // Get file size
    const stats = await fs.stat(outputPath);
    const fileSize = stats.size;

    console.log(`✅ Word document generated successfully (fallback): ${outputPath} (${(fileSize / 1024).toFixed(2)} KB)`);

    return {
      success: true,
      filePath: outputPath,
      fileSize
    };
  } catch (error) {
    console.error('❌ Error generating Word document (fallback):', error);
    throw new Error(`Word generation (fallback) failed: ${error.message}`);
  }
}

module.exports = {
  generateWordFromHtml,
  generateWordFromData
};

